---
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

Docker kibana-5.x:
  stage: deployment test
  script:
    - molecule test -s docker-5.x
  tags:
    - docker

Docker kibana-6.x:
  stage: deployment test
  script:
    - molecule test -s docker-6.x
  tags:
    - docker

EPC kibana-5.x:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-5.x
  tags:
    - delegated

EPC kibana-6.x:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-6.x
  tags:
    - delegated

AWS kibana-5.x:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-5.x
  tags:
    - delegated

AWS kibana-6.x:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-6.x
  tags:
    - delegated
