---
- name: "Configure repository for current OS"
  include_tasks: "{{ platform }}"
  with_first_found:
    - "system/{{ ansible_os_family }}.yml"
    - "system/not-supported.yml"
  loop_control:
    loop_var: "platform"

- name: "Install kibana"
  include_tasks: "install-kibana.yml"

- name: "Wait for kibana is UP"
  uri:
    url: "http://{{ kibana_host }}:{{ kibana_port }}/api/status"
    status_code: "200"
    validate_certs: False
    return_content: True
  register: "kibana_page"
  until: kibana_page.status == 200
  retries: "30"
  delay: "60"
