---
- name: Load a variable file based on the service manager
  include_vars: '{{ service_manager }}'
  with_first_found:
    - '{{ ansible_service_mgr }}.yml'
    - systemv.yml
  loop_control:
    loop_var: service_manager

- name: Load a variable file based on the OS type, or a default if not found
  include_vars: '{{ platform_vars }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: platform_vars

- name: Install kibana packages for current OS
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - system/not-supported.yml
  loop_control:
    loop_var: platform

- name: Install kibana
  include_tasks: install-kibana.yml

- name: Ensure that kibana is started and enabled on startup
  service:
    name: kibana
    state: started
  become: true
