---
- name: "Testing kibana role on CentOS"
  hosts: ansible_role_kibana_v5_centos
  gather_facts: True
  roles:
    - role: kibana
  vars:
    kibana_host: localhost

- name: "Testing kibana role on Ubuntu"
  hosts: ansible_role_kibana_v5_ubuntu
  gather_facts: True
  roles:
    - role: kibana
  vars:
    kibana_host: localhost
