---
- name: Prepare limits
  hosts: rhel_family
  tasks:
    - name: Set Limits
      lineinfile:
        path: /etc/security/limits.conf
        line: elasticsearch soft nproc 65535
      become: true

- name: Prepare Host
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      transport: repositories
    - role: lean_delivery.elasticsearch
      elasticsearch_host: '{{ ansible_host }}'
      elastic_branch: 7
