---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-kibana6
    image: leandelivery/docker-systemd:centos7
    privileged: True
    env:
      TERM: xterm
    groups:
      - ansible_role_kibana_v6_centos
  - name: test-docker-ubuntu1804-kibana6
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    env:
      TERM: xterm
    groups:
      - ansible_role_kibana_v6_ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: docker-6.x
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8 
